# Generated by Django 2.2.24 on 2021-12-26 19:45

import Students.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('disability', models.CharField(blank=True, max_length=400, null=True)),
                ('illness', models.CharField(blank=True, max_length=500, null=True)),
                ('allergies', models.CharField(blank=True, max_length=410, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=Students.models.Student.image_directory)),
                ('prefect', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_confirmation', models.BooleanField(blank=True, null=True, verbose_name='parent confirmation status')),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Male', models.CharField(blank=True, max_length=20, null=True)),
                ('Female', models.CharField(blank=True, max_length=30, null=True)),
                ('male_tel_number', models.CharField(blank=True, max_length=30, null=True)),
                ('female_tel_number', models.CharField(blank=True, max_length=30, null=True)),
                ('male_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('female_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marriage', models.CharField(blank=True, choices=[('sngl', 'Single'), ('tgther', 'Together'), ('splttd', 'Splitted'), ('dvcd', 'Divorced'), ('dcsd_ptner', 'Deceased_partner')], max_length=15, null=True)),
                ('ward', models.ManyToManyField(to='Students.Student')),
            ],
        ),
    ]
