# Generated by Django 2.2.24 on 2021-12-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student',
            new_name='user',
        ),
    ]
