# Generated by Django 2.2.24 on 2022-02-06 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20220206_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2cc3eadf-5d25-4d33-805a-5d9c63a68e9c'), max_length=4000),
        ),
    ]
