# Generated by Django 2.2.24 on 2022-02-02 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20220202_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('813b0970-112a-4460-8e30-a82f47d64a64'), max_length=4000),
        ),
    ]
