# Generated by Django 2.2.24 on 2022-02-06 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20220206_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5896521f-b386-4612-9c43-808811031dd9'), max_length=4000),
        ),
    ]
