# Generated by Django 2.2.24 on 2022-02-06 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_auto_20220206_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('913cd499-1438-4423-8420-7d7982e39386'), max_length=4000),
        ),
    ]
