# Generated by Django 2.2.24 on 2022-02-02 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_auto_20220202_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1f42481a-0f59-48b4-a33a-56056b3036e3'), max_length=4000),
        ),
    ]
