# Generated by Django 2.2.24 on 2022-02-06 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_auto_20220206_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d2d165ba-c1f1-40c5-847d-d20e9da56f5b'), max_length=4000),
        ),
    ]
