# Generated by Django 2.2.24 on 2022-02-02 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_auto_20220202_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8b72c131-2862-4716-99ae-357ef697c537'), max_length=4000),
        ),
    ]
