# Generated by Django 2.2.24 on 2022-02-07 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_auto_20220206_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('15c3b0d7-3147-43cf-a6ea-2010e65d8b79'), max_length=4000),
        ),
    ]
