# Generated by Django 2.2.24 on 2022-02-08 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_auto_20220207_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rep',
            new_name='is_class_rep',
        ),
        migrations.AddField(
            model_name='student',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('066eb24f-966b-4e0f-818b-c6ba9a876a3c'), max_length=4000),
        ),
    ]
