# Generated by Django 3.2.12 on 2022-02-19 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0008_auto_20220208_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefect',
            name='prefect_type',
            field=models.CharField(blank=True, choices=[('G', 'Global'), ('C', 'ClassRoom'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Together', 'Together'), ('Married', 'Married'), ('Splitted', 'Splitted'), ('Divorced', 'Divorced'), ('Deceased_partner', 'Deceased_partner')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('37df86ea-d575-4afc-a379-c03e776bf017'), max_length=4000),
        ),
    ]
