# Generated by Django 3.2.12 on 2022-02-19 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_auto_20220219_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d293cee0-0ecf-4a4c-9249-75ac18bb4078'), max_length=4000),
        ),
    ]
