# Generated by Django 3.2.12 on 2022-02-20 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('56bbceb8-097e-46b0-be80-2bb74bc5462a'), max_length=4000),
        ),
    ]
