# Generated by Django 3.2.12 on 2022-03-07 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0011_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('be5832fb-f27e-4595-bcff-ee7011cb1468'), max_length=4000),
        ),
    ]
