# Generated by Django 3.2.12 on 2022-04-04 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0012_alter_student_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bc0a9562-2018-4764-a54b-b229964ace47'), max_length=4000),
        ),
    ]
