# Generated by Django 3.2.12 on 2022-04-04 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_auto_20220404_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('cb08f2c1-693c-4a1d-831f-e0e62523c3f0'), max_length=4000),
        ),
    ]
