# Generated by Django 4.0.5 on 2022-06-18 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0014_alter_student_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='female_partner',
            new_name='female_partner_firstname',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='male_partner',
            new_name='gaurdian_firstname',
        ),
        migrations.AddField(
            model_name='parent',
            name='female_partner_lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='gaurdian_lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='male_partner_firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='male_partner_lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Gaurdian', 'Gaurdian'), ('Single', 'Single'), ('Together', 'Together'), ('Married', 'Married'), ('Splitted', 'Splitted'), ('Divorced', 'Divorced'), ('Deceased_partner', 'Deceased_partner')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='prefect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('abb9221e-60c5-4c96-9932-6afb79691ed4'), max_length=4000),
        ),
    ]
