# Generated by Django 4.0.5 on 2022-06-19 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0015_rename_female_partner_parent_female_partner_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('9e28b52c-f2cc-4497-934b-ff6c35eda9e8'), max_length=4000),
        ),
    ]
