# Generated by Django 4.0.5 on 2022-06-23 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0016_alter_student_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='female_partner_firstname',
            new_name='female_partner_full_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='gaurdian_firstname',
            new_name='male_partner_full_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='female_partner_lastname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='gaurdian_lastname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='male_partner_firstname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='male_partner_lastname',
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('68e09796-1211-4fe9-888e-9de3db138cda'), max_length=4000),
        ),
    ]
