# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0017_rename_female_partner_firstname_parent_female_partner_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='female_date_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='male_date_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('950bc249-ebd5-41f2-9653-1b6f423ab4c4'), max_length=4000),
        ),
    ]
