# Generated by Django 4.0.5 on 2022-06-23 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0018_parent_female_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3e2351ea-6abe-4dfd-8e69-3668aadc3e3a'), max_length=4000),
        ),
    ]
