# Generated by Django 4.0.5 on 2022-06-26 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0019_student_other_names_alter_student_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='location',
            new_name='current_location',
        ),
        migrations.AddField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='other_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('67d05b46-1d14-4bf4-a4ba-79fb96bc10e3'), max_length=4000),
        ),
    ]
