# Generated by Django 4.0.5 on 2022-06-27 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0020_rename_location_student_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='biological_parent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_marrital_status',
            field=models.CharField(blank=True, choices=[('Gaurdian', 'Gaurdian'), ('Single', 'Single'), ('Together', 'Together'), ('Married', 'Married'), ('Splitted', 'Splitted'), ('Divorced', 'Divorced'), ('Deceased_partner', 'Deceased_partner')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0efdb9ac-1166-4e71-8323-ccd36f826eb0'), max_length=4000),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
