# Generated by Django 4.0.5 on 2022-06-27 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0021_remove_student_parent_student_biological_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('56fe08ff-a299-42cd-8581-b4bc588bac9d'), max_length=4000),
        ),
    ]
