# Generated by Django 4.0.5 on 2022-07-01 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0023_merge_0003_auto_20220205_2007_0022_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('929b1912-143d-447b-afb1-2183ee3926ba'), max_length=4000),
        ),
    ]
