# Generated by Django 4.0.5 on 2022-07-01 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0024_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3e1557b1-bf32-435a-b757-3da85562995f'), max_length=4000),
        ),
    ]
