# Generated by Django 4.0.5 on 2022-07-01 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0025_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d4ac5941-2923-48a8-a5eb-f25a28e3559c'), max_length=4000),
        ),
    ]
