# Generated by Django 4.0.5 on 2022-07-01 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0026_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4beeddd7-a887-41f3-936b-3bac25b3c49b'), max_length=4000),
        ),
    ]
