# Generated by Django 4.0.5 on 2022-07-01 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0028_alter_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uuid',
            field=models.CharField(default=uuid.UUID('9b128705-9d57-44ad-8695-c9eaebee3bd1'), max_length=4000),
        ),
    ]
