# Generated by Django 2.2.24 on 2022-02-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Std_quiz', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student'),
        ),
        migrations.AddField(
            model_name='obj',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Std_quiz.Quiz_Answer'),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Std_quiz.Quiz_Answer'),
        ),
    ]
