# Generated by Django 2.2.24 on 2022-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Std_quiz', '0002_auto_20220206_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_answer',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='quiz_answer',
            old_name='uuid',
            new_name='quiz_uuid',
        ),
        migrations.AddField(
            model_name='quiz_answer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
