# Generated by Django 2.2.24 on 2022-02-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='staff',
            field=models.ManyToManyField(to='Teachers.Staff'),
        ),
    ]
