# Generated by Django 2.2.24 on 2022-02-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=999)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
        ),
        migrations.CreateModel(
            name='SRC_Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=999)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
        ),
        migrations.CreateModel(
            name='Tiution_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=999)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=22)),
                ('level', models.CharField(max_length=22)),
                ('library_fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fees.Library_Fee')),
                ('src_dues', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fees.SRC_Dues')),
            ],
        ),
    ]
