# Generated by Django 2.2.24 on 2022-02-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
        ('Fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.Student'),
        ),
        migrations.AddField(
            model_name='fees',
            name='tiution_fee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fees.Tiution_Fee'),
        ),
    ]
