# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fees', '0002_auto_20220205_1845'),
        ('Fees', '0003_alter_fees_id_alter_library_fee_id_alter_src_dues_id_and_more'),
    ]

    operations = [
    ]
