# Generated by Django 2.2.24 on 2022-02-05 18:45

import Quiz.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=255, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to=Quiz.models.quiz_file)),
                ('uuid', models.CharField(default=uuid.UUID('f2261c73-c65d-4cb3-9bf3-d5b870c896b8'), max_length=223)),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('abf5acd3-9b67-4220-8ce2-36bc474077d7'), max_length=223)),
                ('answer', models.CharField(blank=True, max_length=223, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=223)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('449fab0c-7266-4f47-8f12-0540390f12fc'), max_length=223)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_obj', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=True)),
                ('is_filed', models.BooleanField(default=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('68ceae11-dcb7-410c-bed9-89baf7a8d2da'), max_length=223)),
                ('answer', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz')),
            ],
        ),
    ]
