# Generated by Django 2.2.24 on 2022-02-06 12:03

import Quiz.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=255, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to=Quiz.models.quiz_file)),
                ('uuid', models.CharField(default=uuid.UUID('fcbeeef7-1b1c-48cd-a32c-5a6aa432bf11'), max_length=223)),
            ],
        ),
        migrations.CreateModel(
            name='Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('c233d790-d363-4063-a758-47f94db2acec'), max_length=223)),
                ('answer', models.CharField(blank=True, max_length=223, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=223)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('b26188e3-a213-43f8-9ea3-446bc1e43ea6'), max_length=223)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_obj', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=True)),
                ('is_filed', models.BooleanField(default=False)),
                ('due_date', models.IntegerField(blank=True, null=True)),
                ('timer', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('uuid', models.CharField(default=uuid.UUID('0fbe09cc-90fa-4409-8489-17f348ae35fc'), max_length=223)),
                ('answer', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz')),
            ],
        ),
    ]
