# Generated by Django 2.2.24 on 2022-02-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '0001_initial'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Teachers.Staff'),
        ),
        migrations.AddField(
            model_name='options',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Obj'),
        ),
        migrations.AddField(
            model_name='obj',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
    ]
