# Generated by Django 2.2.24 on 2022-02-06 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20220206_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0451a9df-5fc6-4f44-805f-0169d1622189'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7456a4b9-1efe-499b-8970-2a9a999737a2'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('da14314a-c5aa-4876-94fd-f4aef11e864e'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('49222149-e9fe-4ac2-9b9d-bb19e4531c7f'), max_length=223),
        ),
    ]
