# Generated by Django 2.2.24 on 2022-02-06 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20220206_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='obj',
            name='question_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='options',
            name='option_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='radomize_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='radomize_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='written',
            name='question_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('eb46ec9e-5912-4ebb-bb55-12692b51fd3a'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('86843341-ca16-42df-9431-6b8c7b0b8b9d'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0b589e37-21af-489b-a026-c79fafc95629'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d119ba8f-0a5f-4b36-a887-49373ffaad6b'), max_length=223),
        ),
    ]
