# Generated by Django 2.2.24 on 2022-02-05 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20220205_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='Course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e0f90991-d706-454a-8362-cabf7140839d'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('53ec9caa-3721-4905-ab56-9c51239e561a'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e5963dd6-cd02-4526-9595-b9ecc133203e'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('13b50b74-fc79-4118-91e7-2259ee02f12b'), max_length=223),
        ),
    ]
