# Generated by Django 2.2.24 on 2022-02-06 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20220206_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b4e2bed9-1528-4f36-b789-deaa35bd51c2'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ad89cbb6-c29c-41b0-bb9b-e6bfe5efaf8b'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ef2ccc4c-b8b3-4d1a-8220-b9f19657b657'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3ec47ae0-f47f-4531-9f75-a3d1b7c65ddf'), max_length=223),
        ),
    ]
