# Generated by Django 2.2.24 on 2022-02-06 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20220206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c94584b6-e8cf-4479-843e-680972ebf3f4'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4d4115c6-491c-4ea5-84cf-425c9d941a3c'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bcc16a01-4fd8-49c7-86da-6c63eb864dc0'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d417538f-abeb-49b8-a4f2-13ff6576be75'), max_length=223),
        ),
    ]
