# Generated by Django 2.2.24 on 2022-02-07 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20220206_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('295c21c6-7f83-42aa-be81-09b8f340b430'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('40caab24-e6ab-4bcc-9645-93a8e4365b3d'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('af3d96bf-2fc4-4c30-a34f-ec3f81edc733'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b53a188d-6ab7-45cb-bb0f-f5dcdfdca733'), max_length=223),
        ),
    ]
