# Generated by Django 3.2.12 on 2022-02-19 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20220219_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a3e51826-83a2-4091-825b-70fc0571718e'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('db4b83b1-3957-4fe6-a1eb-c639750a959f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5eb19bb6-d16e-4540-a7e1-aa9892c7a68a'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('435a4759-27a8-4660-b7f8-1a352569692a'), max_length=223),
        ),
    ]
