# Generated by Django 3.2.12 on 2022-02-20 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20220219_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c2dc00bb-b528-41ec-8f5f-325f506633cf'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0ba1a00f-6076-427c-af9a-d7b6ada3784f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6c36f96d-0e75-46b5-84d3-049e54f625cd'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('319d6b57-c561-4b0d-b01f-b78080011a50'), max_length=223),
        ),
    ]
