# Generated by Django 3.2.12 on 2022-03-07 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_auto_20220220_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('147ec9be-165f-4a98-aea8-454b8c5d78fc'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('419b1bd0-242d-4fd9-83ee-9df1d71d4af1'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1ddb8d3e-f8c2-4c21-8e80-e10edf937396'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4163ed76-1946-49c9-8f1f-c9cf4e824310'), max_length=223),
        ),
    ]
