# Generated by Django 3.2.12 on 2022-04-04 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_auto_20220307_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8c3e8523-ba7d-464b-8630-c90574635539'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e8f256c7-772c-4cc0-a4c4-739cdfcc5969'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('1a728d74-46aa-4da9-9e85-65dac7e4d408'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('03278308-cea9-4956-9960-61b2f12689a0'), max_length=223),
        ),
    ]
