# Generated by Django 3.2.12 on 2022-04-04 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_auto_20220404_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('68396ef1-c2ba-47c4-b664-5d4c70492465'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6c4addd7-0c8b-404a-b6c9-5444fd994d9b'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2dbffd5f-4449-4da7-bc75-392158a3010f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('879e44b0-e60a-4535-98e8-c5e69aa01fbb'), max_length=223),
        ),
    ]
