# Generated by Django 4.0.5 on 2022-06-23 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_alter_file_upload_id_alter_file_upload_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('19a0d7f7-a186-4c89-ac1d-2d826ec0c208'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('af0be785-9265-4954-91da-925b2c528808'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('bcbb46a2-a164-487c-9adf-4b417a90d585'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ffd851a6-8867-4d79-b5d9-fc7e2fbb1278'), max_length=223),
        ),
    ]
