# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('3008b738-83ea-43b3-b41c-1ce1b35b1542'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('64b4ee03-d31d-40f5-a21b-82a0328ffd8e'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c9082698-e8c9-4160-a1ff-824351cc3969'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8e4bb69d-da34-4172-9f59-4601a9562669'), max_length=223),
        ),
    ]
