# Generated by Django 4.0.5 on 2022-06-26 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8e7fc409-3229-41a2-ab3f-b65c2c25183f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ba6278b2-cb7e-46b4-87ce-0ab8f2136e67'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5ed00a34-bef5-44f2-93db-2132feefbabc'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f832d679-42db-4e47-bde4-46b76bcef59b'), max_length=223),
        ),
    ]
