# Generated by Django 4.0.5 on 2022-06-27 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0019_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('c7e6c7e8-32f7-483f-af20-386422d0642f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a455a6bd-ba5a-4f09-9bba-7dee711bc2be'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ea42b0fd-2193-4b63-853c-45274d510708'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f13ecd21-876a-4dd4-9946-b8b50b8af743'), max_length=223),
        ),
    ]
