# Generated by Django 4.0.5 on 2022-06-27 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0020_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('9449e102-cad5-4827-982c-935346fc14d3'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5a784de0-9cb8-4783-8c74-4d47d1c01e50'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('6b623356-e1d2-4778-a687-0a583823e765'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e1093451-36d8-4eae-8bca-c5eb8e6ead26'), max_length=223),
        ),
    ]
