# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_auto_20220205_2007'),
        ('Quiz', '0021_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
    ]
