# Generated by Django 4.0.5 on 2022-07-01 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0023_alter_staff_uuid'),
        ('Quiz', '0022_merge_20220701_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='Question',
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('d31b45f5-fbc9-406e-bb7c-a5ee45f98347'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('aba3790d-6fa9-4ded-9551-8c2b2ffb6ce4'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.staff'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('03bbd655-a9f5-4631-9c60-e449ad07afda'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b51507aa-963c-4d4a-8e35-1b299591732e'), max_length=223),
        ),
    ]
