# Generated by Django 4.0.5 on 2022-07-01 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0023_remove_options_question_alter_file_upload_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('001e9646-0c46-42d8-9061-fd840e712b20'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4c6e86df-3ad0-496d-b620-02bfa273c825'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('de2430d7-fa31-4633-9693-be77eaa3feed'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4d45d8ca-6a15-4aa4-927c-8668d09ce8d4'), max_length=223),
        ),
    ]
