# Generated by Django 4.0.5 on 2022-07-01 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0025_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ce8e1887-ed29-4567-892c-acbbbb6fb85f'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('45c673cb-c6c4-455a-881b-ace1ea22d01a'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('01281db2-76a7-4e3d-b851-495dd2232ec7'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f1449780-3c68-4dc5-be96-26ef67952517'), max_length=223),
        ),
    ]
