# Generated by Django 4.0.5 on 2022-07-01 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0026_alter_file_upload_uuid_alter_obj_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='uuid',
            field=models.CharField(default=uuid.UUID('5c15c9c1-6d95-4721-a429-2aeb40c863ed'), max_length=223),
        ),
        migrations.AlterField(
            model_name='obj',
            name='uuid',
            field=models.CharField(default=uuid.UUID('868fd398-980c-4106-8375-ef64f96ab6b4'), max_length=223),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=models.CharField(default=uuid.UUID('221a32ed-45a8-4540-b165-5ad10b0dff42'), max_length=223),
        ),
        migrations.AlterField(
            model_name='written',
            name='uuid',
            field=models.CharField(default=uuid.UUID('38dec846-8196-431e-8cc1-159c19f880c4'), max_length=223),
        ),
    ]
