# Generated by Django 2.2.24 on 2022-02-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Semester_1', '0001_initial'),
        ('Semester_2', '0001_initial'),
        ('Semester_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sem_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Semester_1.Sem_1')),
                ('sem_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Semester_2.Sem_2')),
                ('sem_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Semester_3.Sem_3')),
            ],
        ),
    ]
