# Generated by Django 2.2.24 on 2022-02-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Level', '0002_level_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='sem_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Semester_1.Sem_1'),
        ),
        migrations.AlterField(
            model_name='level',
            name='sem_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Semester_2.Sem_2'),
        ),
        migrations.AlterField(
            model_name='level',
            name='sem_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Semester_3.Sem_3'),
        ),
    ]
