# Generated by Django 3.2.12 on 2022-02-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Level', '0003_auto_20220207_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
