# Generated by Django 2.2.24 on 2022-02-06 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 12, 6, 35, 75287, tzinfo=utc)),
        ),
    ]
