# Generated by Django 2.2.24 on 2022-02-06 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0002_auto_20220206_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 14, 11, 12, 563664, tzinfo=utc)),
        ),
    ]
