# Generated by Django 2.2.24 on 2021-12-26 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0003_auto_20211226_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 22, 11, 55, 793972, tzinfo=utc)),
        ),
    ]
