# Generated by Django 2.2.24 on 2022-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0003_auto_20220206_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
