# Generated by Django 3.2.12 on 2022-02-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0004_auto_20220206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
