# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0002_auto_20220205_2007'),
        ('base_user_manager', '0006_alter_c_user_id'),
    ]

    operations = [
    ]
