# Generated by Django 4.0.5 on 2022-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user_manager', '0007_merge_0002_auto_20220205_2007_0006_alter_c_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
