# Generated by Django 2.2.24 on 2022-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_auto_20220202_2011'),
        ('ClassRooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_list',
            name='staff',
            field=models.ManyToManyField(to='Teachers.Staff'),
        ),
    ]
