# Generated by Django 2.2.24 on 2022-02-06 12:03

import Teachers.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uuid', models.CharField(default=uuid.UUID('867bffdc-c505-4839-a0af-dbf36a589b12'), max_length=4000)),
                ('position', models.CharField(blank=True, max_length=48, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=244, null=True)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('illness', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('mal', 'Male'), ('fem', 'Female')], max_length=3)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=Teachers.models.photo_upload)),
            ],
        ),
    ]
