# Generated by Django 2.2.24 on 2021-12-26 19:45

import Teachers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to=Teachers.models.profile_image)),
                ('position', models.CharField(max_length=48)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=244, null=True)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('illness', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('mal', 'Male'), ('fem', 'Female')], max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
