# Generated by Django 2.2.24 on 2022-02-05 20:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('aecebcbe-ee4b-49c5-9a11-980b29665f62'), max_length=4000),
        ),
    ]
