# Generated by Django 2.2.24 on 2022-02-06 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2e435915-4683-47d1-b9b3-f4ce3ca7d8d4'), max_length=4000),
        ),
    ]
