# Generated by Django 2.2.24 on 2022-02-05 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_auto_20220205_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e2027272-5548-4acf-9a97-fcedf50360cc'), max_length=4000),
        ),
    ]
