# Generated by Django 2.2.24 on 2022-02-06 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_auto_20220206_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('378f3bb8-031d-4635-98c6-13f88c7aaec9'), max_length=4000),
        ),
    ]
