# Generated by Django 2.2.24 on 2022-02-06 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_auto_20220206_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('fedc0ff2-24d7-4f53-a212-4f5697536f71'), max_length=4000),
        ),
    ]
