# Generated by Django 2.2.24 on 2022-02-02 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_auto_20220202_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('253a062b-7161-4265-ae7f-d8f90d2af804'), max_length=4000),
        ),
    ]
