# Generated by Django 2.2.24 on 2022-02-02 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_auto_20220202_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8cdb9348-c71a-4a7d-9abd-abbc35f6db67'), max_length=4000),
        ),
    ]
