# Generated by Django 2.2.24 on 2022-02-06 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_auto_20220206_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('e30ae9e5-dfba-46e0-8ff3-89b481bdaa28'), max_length=4000),
        ),
    ]
