# Generated by Django 2.2.24 on 2022-02-02 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_auto_20220202_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('186621f8-9f36-4ca7-8a87-d882233a16f8'), max_length=4000),
        ),
    ]
