# Generated by Django 2.2.24 on 2022-02-07 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_auto_20220206_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('16c0fe4e-f256-49ae-87c8-845aafa71396'), max_length=4000),
        ),
    ]
