# Generated by Django 2.2.24 on 2022-02-08 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_auto_20220207_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('8a4827ce-9783-43f1-8323-d008f7fd7b48'), max_length=4000),
        ),
    ]
