# Generated by Django 3.2.12 on 2022-02-19 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0008_auto_20220208_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('b6b9144e-004d-44cc-9d28-0d9f65868fa4'), max_length=4000),
        ),
    ]
