# Generated by Django 3.2.12 on 2022-02-20 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0010_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('ccec2282-7695-4f77-81e4-aa705358efe3'), max_length=4000),
        ),
    ]
