# Generated by Django 3.2.12 on 2022-03-07 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0011_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('0fba5ed3-6153-4207-afe8-592f17bb8e7c'), max_length=4000),
        ),
    ]
