# Generated by Django 3.2.12 on 2022-04-04 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('7eb051a4-761a-427f-9904-c8e9aa22a094'), max_length=4000),
        ),
    ]
