# Generated by Django 3.2.12 on 2022-04-04 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0013_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('f2b9c649-48ac-4af2-a9f5-66849e3ab83c'), max_length=4000),
        ),
    ]
