# Generated by Django 4.0.5 on 2022-06-23 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0015_alter_staff_id_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a5ac5b34-c186-4e15-be68-37a012deaf19'), max_length=4000),
        ),
    ]
