# Generated by Django 4.0.5 on 2022-06-23 00:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0016_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('4849ff47-c4b2-40f9-a54f-adab6e4cb19f'), max_length=4000),
        ),
    ]
