# Generated by Django 4.0.5 on 2022-06-26 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0018_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('2f4cd3b1-ccb7-4b83-9af2-137b4b3d8445'), max_length=4000),
        ),
    ]
