# Generated by Django 4.0.5 on 2022-06-27 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0019_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('21ab9e6c-c14b-48a8-a20e-2658c9a7442d'), max_length=4000),
        ),
    ]
