# Generated by Django 4.0.5 on 2022-06-27 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0020_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('a96e1e7d-bbcf-414d-8cdc-6b897ca09187'), max_length=4000),
        ),
    ]
