# Generated by Django 4.0.5 on 2022-07-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_auto_20220205_2007'),
        ('Teachers', '0021_alter_staff_uuid'),
    ]

    operations = [
    ]
