# Generated by Django 4.0.5 on 2022-07-01 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0022_merge_0003_auto_20220205_2007_0021_alter_staff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uuid',
            field=models.CharField(default=uuid.UUID('09bafd07-7fa5-477f-a48f-393d97f8d997'), max_length=4000),
        ),
    ]
