# Generated by Django 2.2.24 on 2022-02-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Level', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='Course.Course')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Level.Level')),
            ],
        ),
    ]
