# Generated by Django 2.2.24 on 2022-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassRooms', '0002_class_list_staff'),
        ('Semester_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem_1',
            name='class_list',
            field=models.ManyToManyField(to='ClassRooms.Class_list'),
        ),
    ]
